[package]
name = "minimal-kernel-rpi2"
version = "0.1.0"
authors = ["papamitra <papamitra@gmail.com>"]
edition = "2018"

[dependencies]
#lazy_static = {version = "1.2.0", features = ["spin_no_std"]}
spin = "0.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
